project:
  type: website 
  output-dir: docs

website:
  title: "faizaimam"
  navbar:
    left:
      - href: index.qmd
        text: About me
      - href: papers.qmd
        text: Papers
      - text: "CV"
        file: CV.pdf
     
format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

